//
//  Day11InputSample.swift
//  advent-of-code-2023
//
//  Created by Eric Eubank on 12/11/23.
//

import Foundation

struct Day11InputSample: DayOfCodeInput {
    let data = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
}
